# Site settings

title: "Printello"

description: "A web app that turns Trello Boards into dashboards you can print"
keywords: "trello, dashboards, print"

baseurl: "/printello" # the subpath of your site, e.g. /blog
url: "http://johnpe.art"
author: "John Peart"

asset-path: "/assets"
image-path: "/img"
css-path: "/css"
js-path: "/js"

logo: "/site/logo.png"
logo-svg: "/site/logo.svg"
logo-four-oh-four: "/site/404.svg"
social-media: "/site/social-media.png"
touch: "/site/touch.png"
pinned: "/site/pinned.svg"
pinned-colour: "#d53880"

# Social settings
facebook-id: "1053585037989505" # For Facebook OpenGraph integration
facebook-slug: "john.robert.peart" # Automatically pre-pends http://facebook.com/
twitter-username: "johnpeart" # Twitter handle i.e. joebloggs
github-username:  "johnpeart"
github-repo: "https://github.com/johnpeart/printello"
google-site-verification: "GMEFdAl3i-jN_Jkdb_jrS-LWZPUEQ7Bx4fPcyQ7YSCU" # GSV code; proves domain ownership

#Analytics
disable-analytics: true # Switch to "false" to start GA logging
google-analytics: "UA-27553664-1" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from